### ISSUE TITLE
Implement four arithmetic operations

### ISSUE THREAD

**Issue by sehyuk02** [sehyuk02/four-arithmetic-operations#1]
### Description
Implement four arithmetic operations

### Tasks
- [ ] Implement Add function
- [ ] Implement Subtract function
- [ ] Implement Multiply function
- [ ] Implement Divide function
